config/routes.rb
Rails.application.routes.draw do
  root 'parties#index'
  
  resources :parties, only: [:index, :show, :new, :create]
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/party.rb
class Party < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  def index
    @parties = Party.all
  end
  
  def show
    @party = Party.find(params[:id])
  end
  
  def new
    @party = Party.new
  end
  
  def create
    @party = Party.new(party_params)
    
    if @party.save
      flash[:notice] = "Awesomesauce! Party created."
      redirect_to root_path
    else
      render :new
    end
  end
  
  protected
  def party_params
    params.require("party").permit(:name, :location, :description)
  end
end

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlartyTime</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  
    <%= javascript_include_tag "vendor/modernizr" %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">BlartyTime</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  
  <%- if Rails.env.development? || Rails.env.test? -%> 
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>
  
  <%= yield :extra_footer %>
</body>
</html>

app/views/parties/index.html.erb
<h1> All My Parties </h1>
<div>
  <ul>
    <% @parties.each do |specific_party| %>
      <li><%= link_to specific_party.name, party_path(specific_party) %></li>
    <% end %>
  </ul>
</div>

<%= link_to "Make Dat Party", new_party_path %>

app/views/parties/new.html.erb
<h1>Let's Make A New Party</h1>

<div>
  <% if @party.errors %>
    <ul>
      <% @party.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  <% end %>
  
  <%= form_for @party do |f| %>
  <%= f.label :name, "What's your awesome party called?" %>
  <%= f.text_field :name %>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  
  <%= f.submit %>
  <% end %>
</div>

app/views/parties/show.html.erb
<div>
  <h1>It's My Party!</h1>
  <p>Name:</p>
  <p> <%= @party.name %> </p>
  <p>Location:</p>
  <p> <%= @party.location %> </p>
  <p>Description:</p>
  <p> <%= @party.description %> </p>
  
</div>